### ISSUE TITLE
Compiling book fails: Data files stored in wrong directory

### ISSUE THREAD

**Issue by tmalsburg** [vasishth/Freq_CogSci#30]
The files `maxmodelsiglog.rda` and `maxmodelsigraw.rda` should be stored in the `data` subdirectory but are instead stored in the root directory.  Therefore loading them later fails.

See [here](https://github.com/vasishth/Freq_CogSci/blob/master/09-multiplecomparisons.Rmd#L384) and [here](https://github.com/vasishth/Freq_CogSci/blob/master/09-multiplecomparisons.Rmd#L390).

**Comment by vasishth** [comment]
this is fixed now.
